# Generated by Django 4.1.13 on 2024-07-13 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lmsapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_field", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login", models.DateField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", lmsapp.models.users()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "AccessionNumber",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("TitleId", models.CharField(max_length=10, null=True)),
                ("TitleName", models.CharField(max_length=250, null=True)),
                ("AllowLend", models.BooleanField(default=True, max_length=1)),
                ("AuthorName", models.CharField(blank=True, max_length=100, null=True)),
                ("AuthorId", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "SupplierName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ClassificaNumber",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
            },
        ),
        migrations.CreateModel(
            name="Userdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "rollnumber",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="RollNo."
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Homme"), ("F", "Femme")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("branch", models.CharField(max_length=10, verbose_name="Branch")),
                ("section", models.CharField(max_length=50, verbose_name="Section")),
                (
                    "libraryid",
                    models.CharField(max_length=50, verbose_name="Library ID"),
                ),
                (
                    "usermail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userdata",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Infromation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookLending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lending_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("return_time", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lendinginfo",
                        to="lmsapp.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lendinginfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
