# Generated by Django 4.1.13 on 2024-07-13 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lmsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="academic_year",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Academic Year"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="gender",
            field=models.CharField(
                choices=[("M", "👨"), ("F", "👧")], max_length=1, verbose_name="Gender"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="usermail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userdata",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Information",
            ),
        ),
    ]
