# Generated by Django 4.1.13 on 2024-07-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lmsapp", "0002_userdata_academic_year_alter_userdata_gender_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booklending",
            unique_together={("user", "book", "lending_time")},
        ),
        migrations.AddField(
            model_name="booklending",
            name="expected_return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booklending",
            name="fine_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
